### ISSUE TITLE
Use `GeoTransform` to get resolution for GeoBox?

### ISSUE THREAD

**Issue by snowman2** [opendatacube/odc-geo#53]
Related to: opendatacube/datacube-core#752

Currently the `resolution` inside of the coordinate attributes are used:

https://github.com/opendatacube/datacube-core/blob/05093b75a8f15b643c7047502ae27b662af2d9b4/datacube/utils/xarray_geoextensions.py#L133-L139

`GeoTransform` is a property used by GDAL to store this information (https://gdal.org/drivers/raster/netcdf.html#georeference)

Here is an example of reading in this property:
https://github.com/corteva/rioxarray/blob/f658d5f829a88204b2ec7b239735aba31694ed0a/rioxarray/rioxarray.py#L540-L545

Thoughts about supporting this as well?

**Comment by Kirill888** [comment]
@snowman2 problem with just reading transform attribute is cropping. If I loaded some netcdf data with GeoTransform property set, then cropped it to a single pixel, I would get wrong transform (location for pixel 0,0 and not for my pixel).

Extracting just resolution component of GeoTransform, might be ok. But honestly I think proper way to handle this issue is to record not just pixel centers but also pixel edges at load/assign_crs time, or at least have an option to do so with minimal effort. 

I doubt any of this will happen in `datacube` repo, this is now in `odc-geo`, and `datacube` will migrate to `odc-geo` soon/eventually. Similar logic in `odc-geo`:

https://github.com/opendatacube/odc-geo/blob/4f9004720d899dff4bf0b208e4fe602790d055d7/odc/geo/_xr_interop.py#L303-L306

**Comment by snowman2** [comment]
@Kirill888 are you able to move this issue to odc-geo?

**Comment by snowman2** [comment]
Related code from rioxarray for reading the transform:
https://github.com/corteva/rioxarray/blob/f658d5f829a88204b2ec7b239735aba31694ed0a/rioxarray/rioxarray.py#L602-L633

It uses the `GeoTransform` only if the data is not 2D (to get the resolution component) or if the data is not rectilinear or if it is rotated.
Though, it does look like it could potentially benefit from this logic to recalculate the transform from the input transform when the data is not rectilinear of it it is rotated: https://github.com/opendatacube/odc-geo/blob/4f9004720d899dff4bf0b208e4fe602790d055d7/odc/geo/_xr_interop.py#L324-L330

**Comment by Kirill888** [comment]
By the way this logic here only works when affine matrix is pure rotation and does not have "shear" component:

https://github.com/corteva/rioxarray/blob/f658d5f829a88204b2ec7b239735aba31694ed0a/rioxarray/rioxarray.py#L75-L76


To deal with shear `odc-geo` has this:

https://github.com/opendatacube/odc-geo/blob/4f9004720d899dff4bf0b208e4fe602790d055d7/odc/geo/math.py#L339-L360
