### ISSUE TITLE
GridSpec.tiles produces multiple tiles unexpected

### ISSUE THREAD

**Issue by emmaai** [opendatacube/odc-geo#97]
Test code:
----
```
from odc.geo.gridspec import GridSpec
from odc.geo import BoundingBox
bb = BoundingBox(left=1200000.0, bottom=-3720000.0, right=1320000.0, top=-3600000.0, crs='EPSG:3577')
grid_spec = GridSpec(crs='EPSG:3577',
                     tile_shape=(4000, 4000),
                     resolution=30)
idx_bounds = grid_spec.idx_bounds(bb)
gbox = [gbox for _, gbox in grid_spec.tiles(bb)]
```
Outputs
----
```
idx_bounds

BoundingBox(left=10, bottom=-31, right=11, top=-30, crs=CRS('EPSG:3577'))

gbox

[GeoBox((4000, 4000), Affine(30.0, 0.0, 1200000.0,
        0.0, -30.0, -3600000.0), CRS('EPSG:3577')),
 GeoBox((4000, 4000), Affine(30.0, 0.0, 1320000.0,
        0.0, -30.0, -3600000.0), CRS('EPSG:3577')),
 GeoBox((4000, 4000), Affine(30.0, 0.0, 1200000.0,
        0.0, -30.0, -3480000.0), CRS('EPSG:3577')),
 GeoBox((4000, 4000), Affine(30.0, 0.0, 1320000.0,
        0.0, -30.0, -3480000.0), CRS('EPSG:3577'))]
```

Expected outputs
----
```
[GeoBox((4000, 4000), Affine(30.0, 0.0, 1200000.0,
        0.0, -30.0, -3600000.0), CRS('EPSG:3577'))]
```

The cause:
----
https://github.com/opendatacube/odc-geo/blob/b59a87cda71428b309682f5156b46ae9a11ef034/odc/geo/gridspec.py#L198-L201

The right and top boundary idx was forced `+1` as shown above.

The question:
---
Is it a new convention that `BoundingBox` upper bound (bottom right) close instead of open now?

**Comment by Kirill888** [comment]
Good catch @emmaai, but the problem is not in that loop alone, this is tightly coupled to this code:

https://github.com/opendatacube/odc-geo/blob/b59a87cda71428b309682f5156b46ae9a11ef034/odc/geo/gridspec.py#L148-L163

Basically `idx_bounds` is under-defined. I think it should return open bound for bottom/right, and maybe not use BoundingBox but a tuple of slices.

Essentially this logic breaks down when supplied bounding box is covering tile exactly. In the code above we should really subtract epsilon from the right and bottom edges when locating bottom-right tile.

```python
ix2, iy2 = self.pt2idx(x2 - eps, y2 - eps).xy
```

then return

```python
return BoundingBox(ix1, iy1, ix2+1, iy2+1, None)
```

That bounding box should not really have CRS as it's not using CRS units at this point.

Relevant change:

https://github.com/opendatacube/odc-geo/commit/a96c2244a4e50829eb15a28a1518c022b949daad

Using BoundingBox as output of `.idx_bounds()` was a mistake, especially with close left/right, because how would you represent a single tile region?
